# Generated by Django 4.2.5 on 2023-10-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_alter_action_id_alter_auction_id_alter_character_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(unique=True, verbose_name='username'),
        ),
    ]
