# Generated by Django 4.2.5 on 2023-10-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_alter_equipment_amulet_alter_equipment_boots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='consumables',
            field=models.JSONField(default=django.db.models.deletion.SET_NULL),
        ),
    ]
