# Generated by Django 4.2.5 on 2023-10-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0007_alter_equipment_amulet_alter_equipment_boots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='amulet',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_amulets', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='boots',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_boots', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='bracers',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_bracers', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='breastplate',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_breastplates', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='chainmail',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_chainmails', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='consumables',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='helmet',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_helmets', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='leggings',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_leggings', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ring',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_rings', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='shoulders',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_shoulders', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weapon_left',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_left_weapons', to='rpg.item'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weapon_right',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='%(class)s_right_weapons', to='rpg.item'),
        ),
    ]
