# Generated by Django 4.2.5 on 2023-10-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0009_npc_enemy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), to='rpg.equipment'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.JSONField(null=True),
        ),
    ]
