# Generated by Django 4.2.5 on 2023-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_alter_character_created_at_alter_character_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.CharField(default='location.png', verbose_name='location image'),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='location name', verbose_name='location name'),
        ),
    ]
