# Generated by Django 4.2.5 on 2023-10-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0011_location_image_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='item.png', verbose_name='item image'),
        ),
    ]
