# Generated by Django 4.2.5 on 2023-10-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0013_alter_character_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(default='unequipable'),
        ),
    ]
